spring:
  datasource:
    url: "jdbc:h2:mem:testdb"
    driverClassName: "org.h2.Driver"
    username: "h2"
    password: "h2"
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
  h1:
    console:
      enabled: true
      path: /h2-console