azure:
  cosmosdb:
    uri: "https://av035p-cosmosdb.documents.azure.com:443/"
    key: "A7jUCWLbo1yZwjS1j3KhCJxOYPzt9OaLMB3KpQjvydCfspasvr9xvMtj9LEKAqXU5BeGdp40SBDVvfLcpmy4cg=="
    database: "TMUsers"