azure:
  cosmosdb:
    uri: "https://temp-db-44604.documents.azure.com:443/"
    key: "WwikSz22etRgn9Xz11EHpFGD098CxFFx16CVOR8bNn88W4XAfZD2n8kvw1ujy03XLsvnW36wm0drGuNvSYiPRQ=="
    database: "TMUsers"
